import { contractAddresses } from './contractAddresses';
export const getPoolList = () =>
{
    return [
        {
            id: 'AcaPool10',
            label: 'Acacia (ACA) Pool',
            tokenLabel: 'ACA',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.Aca,
            poolAddr: contractAddresses.AcaPool,
            dashboardAddr: '',
            term: '10 days',
            //may need to add token image
        },
        {
            id: 'AcaPool30',
            label: 'Acacia (ACA) Pool',
            tokenLabel: 'ACA',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.Aca,
            poolAddr: contractAddresses.AcaPool,
            dashboardAddr: '',
            term: '30 days',
            //may need to add token image
        },
        {
            id: 'AcaPool90',
            label: 'Acacia (ACA) Pool',
            tokenLabel: 'ACA',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.Aca,
            poolAddr: contractAddresses.AcaPool,
            dashboardAddr: '',
            term: '90 days',
            //may need to add token image
        },
        {
            id: 'KlayAcaLpPool10',
            label: 'KLAY-ACA LP Pool',
            tokenLabel: 'KLAY-ACA',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KlayAca,
            poolAddr: contractAddresses.KlayAcaLpPool,
            dashboardAddr: '',
            term: '10 days',
        },
        {
            id: 'KlayAcaLpPool30',
            label: 'KLAY-ACA LP Pool',
            tokenLabel: 'KLAY-ACA',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KlayAca,
            poolAddr: contractAddresses.KlayAcaLpPool,
            dashboardAddr: '',
            term: '30 days',
        },
        {
            id: 'KlayAcaLpPool90',
            label: 'KLAY-ACA LP Pool',
            tokenLabel: 'KLAY-ACA',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KlayAca,
            poolAddr: contractAddresses.KlayAcaLpPool,
            dashboardAddr: '',
            term: '90 days',
        },
        {
            id: 'KlayKspLpPool10',
            label: 'KLAY-KSP LP Pool',
            tokenLabel: 'KLAY-KSP',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KlayKsp,
            poolAddr: contractAddresses.KlayKspLpPool,
            dashboardAddr: '',
            term: '10 days',
        },
        {
            id: 'KlayKspLpPool30',
            label: 'KLAY-KSP LP Pool',
            tokenLabel: 'KLAY-KSP',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KlayKsp,
            poolAddr: contractAddresses.KlayKspLpPool,
            dashboardAddr: '',
            term: '30 days',
        },
        {
            id: 'KlayKspLpPool90',
            label: 'KLAY-KSP LP Pool',
            tokenLabel: 'KLAY-KSP',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KlayKsp,
            poolAddr: contractAddresses.KlayKspLpPool,
            dashboardAddr: '',
            term: '90 days',
        },
        {
            id: 'KusdtAcaLpPool10',
            label: 'KUSDT-ACA LP Pool',
            tokenLabel: 'KUSDT-ACA',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KusdtAca,
            poolAddr: contractAddresses.KusdtAcaLpPool,
            dashboardAddr: '',
            term: '10 days',
        },
        {
            id: 'KusdtAcaLpPool30',
            label: 'KUSDT-ACA LP Pool',
            tokenLabel: 'KUSDT-ACA',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KusdtAca,
            poolAddr: contractAddresses.KusdtAcaLpPool,
            dashboardAddr: '',
            term: '30 days',
        },
        {
            id: 'KusdtAcaLpPool90',
            label: 'KUSDT-ACA LP Pool',
            tokenLabel: 'KUSDT-ACA',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KusdtAca,
            poolAddr: contractAddresses.KusdtAcaLpPool,
            dashboardAddr: '',
            term: '90 days',
        },
        {
            id: 'KusdtKdaiLpPool10',
            label: 'KUSDT-KDAI LP Pool',
            tokenLabel: 'KUSDT-KDAI',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KusdtKdai,
            poolAddr: contractAddresses.KusdtKdaiLpPool,
            dashboardAddr: '',
            term: '10 days'
        },
        {
            id: 'KusdtKdaiLpPool30',
            label: 'KUSDT-KDAI LP Pool',
            tokenLabel: 'KUSDT-KDAI',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KusdtKdai,
            poolAddr: contractAddresses.KusdtKdaiLpPool,
            dashboardAddr: '',
            term: '30 days'
        },
        {
            id: 'KusdtKdaiLpPool90',
            label: 'KUSDT-KDAI LP Pool',
            tokenLabel: 'KUSDT-KDAI',
            profitLabel: ['ACA'],
            // twoTokenProfit: false,
            decimals: 18,
            tokenAddr: contractAddresses.KusdtKdai,
            poolAddr: contractAddresses.KusdtKdaiLpPool,
            dashboardAddr: '',
            term: '90 days'
        },
    ]
}